[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
warp = "0.3.7"
tokio-tungstenite = "0.23.1"
futures = "0.3"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
